# Generated by Django 5.2.8 on 2025-11-29 10:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_budgetcategory_alter_account_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='budgetcategory',
            new_name='main_budget_user_id_365e44_idx',
            old_name='main_budget_user_id_name_idx',
        ),
        migrations.AddField(
            model_name='goal',
            name='linked_accounts',
            field=models.ManyToManyField(blank=True, related_name='linked_goals', to='main.account', verbose_name='Подключённые счета'),
        ),
        migrations.AddField(
            model_name='goal',
            name='use_only_linked_accounts',
            field=models.BooleanField(default=False, help_text='Если включено — прогресс считается только по подключённым счетам', verbose_name='Учитывать только подключённые счета'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('deposit', 'Вклад'), ('debit', 'Дебетовый счет'), ('credit', 'Кредитный счет'), ('savings', 'Накопительный счет'), ('investment', 'Инвестиционный счет'), ('cash', 'Наличные'), ('other', 'Другое')], db_index=True, default='other', max_length=20, verbose_name='Тип счета'),
        ),
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Текущая сумма (заполняется вручную, если нужно)'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Целевая сумма'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='main.account', verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('еда', 'Еда'), ('транспорт', 'Транспорт'), ('развлечения', 'Развлечения'), ('жилье', 'Жилье'), ('здоровье', 'Здоровье'), ('одежда', 'Одежда'), ('доход', 'Доход'), ('другое', 'Другое')], db_index=True, default='другое', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], db_index=True, max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', '-created_at'], name='main_accoun_user_id_2cc21c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-date'], name='main_transa_user_id_6952b1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type', '-date'], name='main_transa_user_id_17f715_idx'),
        ),
    ]
