# Generated by Django 5.2.8 on 2025-12-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatedName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('validation_status', models.CharField(choices=[('valid', 'Валидно'), ('invalid', 'Невалидно')], default='valid', max_length=20, verbose_name='Статус валидации')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Валидированное ФИО',
                'verbose_name_plural': 'Валидированные ФИО',
                'ordering': ['-created_at'],
            },
        ),
    ]
