# Generated by Django 5.2.8 on 2025-12-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_validatedname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidatedName',
        ),
    ]
