# Generated by Django 5.2.8 on 2025-12-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_validatedname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата блокировки'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, verbose_name='Неудачные попытки входа'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Аккаунт заблокирован'),
        ),
    ]
