# Generated by Django 5.2.8 on 2025-11-29 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
        ('main', '0004_rename_main_budget_user_id_name_idx_main_budget_user_id_365e44_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название цели')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Целевая сумма')),
                ('use_only_accounts', models.BooleanField(default=False, verbose_name='Учитывать только подключённые счета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to='forecast.financialgoal')),
            ],
            options={
                'unique_together': {('goal', 'account')},
            },
        ),
        migrations.DeleteModel(
            name='Forecast',
        ),
    ]
