# Generated by Django 5.2.8 - Cleanup duplicate Goal models

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_financialgoal_goalaccount_delete_forecast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialGoal',
        ),
        migrations.DeleteModel(
            name='GoalAccount',
        ),
    ]
